return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		event = { "BufReadPost", "BufNewFile", "VeryLazy" },
		cmd = { "TSBufEnable", "TSBufDisable", "TSUpdate", "TSInstall", "TSModuleInfo" },
		opts = {
			highlight = { enable = true },
			indent = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"diff",
				"go",
				"javascript",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"make",
				"printf",
				"python",
				"query",
				"rust",
				"vim",
				"vimdoc",
			},
		},
	},
}
